# Generated by Django 5.0.6 on 2024-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecounter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('ua', models.CharField(max_length=50)),
                ('ru', models.CharField(max_length=50, null=True)),
                ('en', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
