# Generated by Django 5.0.6 on 2024-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecounter', '0003_alter_counters_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
