# Generated by Django 5.0.6 on 2024-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecounter', '0004_alter_counters_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_dey', models.FloatField()),
                ('cost_night', models.FloatField()),
            ],
        ),
    ]
