# Generated by Django 5.0.6 on 2024-05-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('rooms', models.IntegerField()),
                ('bweller', models.IntegerField(unique=True)),
                ('power', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Bweller',
            fields=[
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('apartment_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='apartment_number', serialize=False, to='user.flats')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Жилец',
                'verbose_name_plural': 'Жильцы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
