# Generated by Django 5.0.6 on 2024-05-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_number_flats_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bweller',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
