# Generated by Django 5.0.6 on 2024-05-09 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0003_bweller_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bweller',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='bweller_set', related_query_name='bweller', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='bweller',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='bweller',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='bweller',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='bweller',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='bweller',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='bweller_set', related_query_name='bweller', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='date_register',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='login',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bweller',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bweller',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='bweller',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='photo'),
        ),
    ]
