# Generated by Django 5.0.6 on 2024-05-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_bweller_groups_bweller_is_active_bweller_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='power',
            field=models.FloatField(),
        ),
    ]
