# Generated by Django 5.0.6 on 2024-05-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_flats_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bweller',
            name='identifier',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='identifier'),
        ),
    ]
