# Generated by Django 5.0.6 on 2024-05-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_bweller_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bweller',
            name='time_identifier',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='time identifier'),
        ),
    ]
