# Generated by Django 5.0.6 on 2024-05-12 10:37

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_bweller_dey_limit_bweller_naight_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bweller',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Bweller', 'verbose_name_plural': 'Bwellers'},
        ),
        migrations.AlterModelOptions(
            name='flats',
            options={'ordering': ['number'], 'verbose_name': 'Flat', 'verbose_name_plural': 'Flats'},
        ),
        migrations.AlterField(
            model_name='bweller',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.get_upload_path, verbose_name='photo'),
        ),
    ]
